// Generated by protocol/tools/generate_schemas.rb from protocol/schemas/*.json. Do not edit.
export default {
  "attested": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/attested.json",
    "title": "attested",
    "description": "pubphys.attested/1 (SPEC section 7).",
    "type": "object",
    "required": [
      "attestation",
      "record_hash",
      "schema"
    ],
    "properties": {
      "schema": {
        "const": "pubphys.attested/1"
      },
      "record_hash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "attestation": {
        "type": "object",
        "required": [
          "batch",
          "client_id",
          "id_token_sha256",
          "kind"
        ],
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "orcid-oidc",
              "platform",
              "none"
            ]
          },
          "batch": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            },
            "minItems": 1
          },
          "id_token_sha256": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^[0-9a-f]{64}$"
          },
          "client_id": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^[A-Za-z0-9-]{1,64}$"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  },
  "bundle": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/bundle.json",
    "title": "bundle",
    "description": "pubphys.bundle/1 (SPEC section 10). Not hashed; its arrays need not be sorted.",
    "type": "object",
    "required": [
      "attested",
      "attesting",
      "content",
      "content_withheld",
      "envelope",
      "files",
      "id_token",
      "id_token_withheld",
      "log",
      "orcid_key_evidence",
      "ots",
      "record",
      "schema"
    ],
    "properties": {
      "schema": {
        "const": "pubphys.bundle/1"
      },
      "record": {
        "type": "object"
      },
      "content": {
        "type": [
          "object",
          "null"
        ]
      },
      "content_withheld": {
        "type": "string",
        "enum": [
          "true",
          "false"
        ]
      },
      "files": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "data",
            "id"
          ],
          "properties": {
            "id": {
              "type": "string",
              "pattern": "^[a-z0-9-]{1,40}$"
            },
            "data": {
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[A-Za-z0-9_-]*$"
            }
          },
          "additionalProperties": false
        }
      },
      "attested": {
        "type": "object"
      },
      "id_token": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$"
      },
      "id_token_withheld": {
        "type": "string",
        "enum": [
          "true",
          "false"
        ]
      },
      "envelope": {
        "type": "object"
      },
      "ots": {
        "type": "object",
        "required": [
          "attested",
          "envelope"
        ],
        "properties": {
          "attested": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[A-Za-z0-9_-]*$"
            }
          },
          "envelope": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[A-Za-z0-9_-]*$"
            }
          }
        },
        "additionalProperties": false
      },
      "log": {
        "type": "object",
        "required": [
          "checkpoint",
          "leaf_index",
          "promise",
          "proof",
          "tree_size"
        ],
        "properties": {
          "leaf_index": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]{0,15})$"
          },
          "tree_size": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]{0,15})$"
          },
          "proof": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            }
          },
          "checkpoint": {
            "type": "string"
          },
          "promise": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "additionalProperties": false
      },
      "orcid_key_evidence": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "captures",
            "jwk"
          ],
          "properties": {
            "jwk": {
              "type": "object"
            },
            "captures": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false
        }
      },
      "attesting": {
        "type": [
          "object",
          "null"
        ]
      }
    },
    "additionalProperties": false
  },
  "content.appeal": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.appeal.json",
    "title": "content.appeal",
    "description": "pubphys.content.appeal/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "reasons"
    ],
    "properties": {
      "reasons": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "content.appointment": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.appointment.json",
    "title": "content.appointment",
    "description": "pubphys.content.appointment/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "action",
      "field",
      "role",
      "subject_orcid"
    ],
    "properties": {
      "subject_orcid": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$"
      },
      "field": {
        "type": "string",
        "pattern": "^([a-z]{2,8}|\\*)$"
      },
      "role": {
        "type": "string",
        "enum": [
          "moderator",
          "referee",
          "chief_moderator"
        ]
      },
      "action": {
        "type": "string",
        "enum": [
          "appoint",
          "revoke"
        ]
      }
    },
    "additionalProperties": false
  },
  "content.attribution": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.attribution.json",
    "title": "content.attribution",
    "description": "pubphys.content.attribution/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "new_account_ref",
      "new_author_orcid",
      "reason",
      "subject"
    ],
    "properties": {
      "subject": {
        "type": "string",
        "pattern": "^([0-9a-f]{64}|seed)$"
      },
      "new_author_orcid": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$"
      },
      "new_account_ref": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[a-z0-9]{8,64}$"
      },
      "reason": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "content.claim": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.claim.json",
    "title": "content.claim",
    "description": "pubphys.content.claim/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "assisted_by",
      "body",
      "kind",
      "problem_ref",
      "references"
    ],
    "properties": {
      "problem_ref": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "kind": {
        "type": "string",
        "enum": [
          "progress",
          "solution",
          "disproof"
        ]
      },
      "body": {
        "type": "string"
      },
      "references": {
        "type": "string"
      },
      "assisted_by": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "additionalProperties": false
  },
  "content.contest": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.contest.json",
    "title": "content.contest",
    "description": "pubphys.content.contest/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "body",
      "grounds",
      "quoted_locator",
      "quoted_text",
      "references"
    ],
    "properties": {
      "grounds": {
        "type": "string",
        "enum": [
          "error",
          "gap",
          "prior_art",
          "missing_credit",
          "irreproducible"
        ]
      },
      "quoted_locator": {
        "type": "string"
      },
      "quoted_text": {
        "type": "string"
      },
      "body": {
        "type": "string"
      },
      "references": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "content.import-manifest": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.import-manifest.json",
    "title": "content.import-manifest",
    "description": "pubphys.content.import-manifest/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "as_of",
      "counts",
      "items_file_id",
      "predicate",
      "source"
    ],
    "properties": {
      "source": {
        "type": "string"
      },
      "as_of": {
        "type": "string"
      },
      "predicate": {
        "type": "string"
      },
      "counts": {
        "type": "object",
        "additionalProperties": {
          "type": "string",
          "pattern": "^(0|[1-9][0-9]*)$"
        }
      },
      "items_file_id": {
        "type": "string",
        "pattern": "^[a-z0-9-]{1,40}$"
      }
    },
    "additionalProperties": false
  },
  "content.jwks": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.jwks.json",
    "title": "content.jwks",
    "description": "pubphys.content.jwks/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "captures",
      "jwks_file_id",
      "url"
    ],
    "properties": {
      "url": {
        "type": "string"
      },
      "jwks_file_id": {
        "type": "string",
        "pattern": "^[a-z0-9-]{1,40}$"
      },
      "captures": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "additionalProperties": false
  },
  "content.platform-key": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.platform-key.json",
    "title": "content.platform-key",
    "description": "pubphys.content.platform-key/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "key_id",
      "new_key_signature",
      "previous_key_id",
      "public_key"
    ],
    "properties": {
      "key_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "public_key": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{43}$"
      },
      "previous_key_id": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{64}$"
      },
      "new_key_signature": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{86}$"
      }
    },
    "additionalProperties": false
  },
  "content.platform-key-revocation": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.platform-key-revocation.json",
    "title": "content.platform-key-revocation",
    "description": "pubphys.content.platform-key-revocation/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "key_id",
      "reason"
    ],
    "properties": {
      "key_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "reason": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "content.reveal": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.reveal.json",
    "title": "content.reveal",
    "description": "pubphys.content.reveal/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "note"
    ],
    "properties": {
      "note": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "content.review": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.review.json",
    "title": "content.review",
    "description": "pubphys.content.review/1. Required params per decision are fixed in SPEC section 6.",
    "type": "object",
    "required": [
      "decision",
      "params",
      "reasons"
    ],
    "properties": {
      "decision": {
        "type": "string",
        "enum": [
          "accept",
          "reject",
          "screening_reject",
          "recommend",
          "not_recommend",
          "triage_substantive",
          "triage_not_substantive",
          "uphold",
          "dismiss",
          "credit",
          "reverse",
          "remove",
          "appeal_grant",
          "appeal_deny",
          "carry_acceptance",
          "reassign_topic",
          "verify_note"
        ]
      },
      "reasons": {
        "type": "string"
      },
      "params": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },
    "additionalProperties": false
  },
  "content.revision": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.revision.json",
    "title": "content.revision",
    "description": "pubphys.content.revision/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "answer_type",
      "assisted_by",
      "external_id",
      "kind",
      "literature_status",
      "n",
      "parents",
      "plain",
      "posed_since",
      "precise",
      "problem_ref",
      "references",
      "settled_by",
      "status_note",
      "title",
      "topic_ref"
    ],
    "properties": {
      "problem_ref": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{64}$"
      },
      "n": {
        "type": "string",
        "pattern": "^[1-9][0-9]*$"
      },
      "external_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "topic_ref": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{64}$"
      },
      "title": {
        "type": "string"
      },
      "plain": {
        "type": "string"
      },
      "precise": {
        "type": "string"
      },
      "settled_by": {
        "type": "string"
      },
      "kind": {
        "type": "string",
        "enum": [
          "well-posed",
          "phenomenon"
        ]
      },
      "answer_type": {
        "type": "string",
        "enum": [
          "yes-no",
          "value",
          "mechanism",
          "classification",
          "proof",
          "identification"
        ]
      },
      "references": {
        "type": "string"
      },
      "literature_status": {
        "type": "string",
        "enum": [
          "open",
          "contested",
          "partially-resolved"
        ]
      },
      "status_note": {
        "type": "string"
      },
      "posed_since": {
        "type": "string"
      },
      "assisted_by": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "parents": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "note",
            "parent_revision",
            "relation"
          ],
          "properties": {
            "parent_revision": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            },
            "relation": {
              "type": "string",
              "enum": [
                "special_case",
                "generalization",
                "combination",
                "variant"
              ]
            },
            "note": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  },
  "content.topic": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.topic.json",
    "title": "content.topic",
    "description": "pubphys.content.topic/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "external_id",
      "field",
      "n",
      "review_cite",
      "review_link",
      "review_verified",
      "summary",
      "title",
      "topic_ref",
      "why"
    ],
    "properties": {
      "topic_ref": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{64}$"
      },
      "n": {
        "type": "string",
        "pattern": "^[1-9][0-9]*$"
      },
      "external_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "field": {
        "type": "string",
        "pattern": "^[a-z]{2,8}$"
      },
      "title": {
        "type": "string"
      },
      "summary": {
        "type": "string"
      },
      "why": {
        "type": "string"
      },
      "review_cite": {
        "type": "string"
      },
      "review_link": {
        "type": "string"
      },
      "review_verified": {
        "type": "string",
        "enum": [
          "true",
          "false"
        ]
      }
    },
    "additionalProperties": false
  },
  "content.upload": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.upload.json",
    "title": "content.upload",
    "description": "pubphys.content.upload/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "ai_consent",
      "file_id",
      "purpose"
    ],
    "properties": {
      "purpose": {
        "type": "string",
        "enum": [
          "problem",
          "claim",
          "contest",
          "appeal"
        ]
      },
      "ai_consent": {
        "type": "string",
        "enum": [
          "true",
          "false"
        ]
      },
      "file_id": {
        "type": "string",
        "pattern": "^[a-z0-9-]{1,40}$"
      }
    },
    "additionalProperties": false
  },
  "content.withdrawal": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/content.withdrawal.json",
    "title": "content.withdrawal",
    "description": "pubphys.content.withdrawal/1 (SPEC section 6).",
    "type": "object",
    "required": [
      "reason"
    ],
    "properties": {
      "reason": {
        "type": "string"
      }
    },
    "additionalProperties": false
  },
  "envelope": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/envelope.json",
    "title": "envelope",
    "description": "pubphys.envelope/1 (SPEC section 8).",
    "type": "object",
    "required": [
      "attested_hash",
      "platform_signature",
      "schema"
    ],
    "properties": {
      "schema": {
        "const": "pubphys.envelope/1"
      },
      "attested_hash": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "platform_signature": {
        "type": "object",
        "required": [
          "key_id",
          "sig"
        ],
        "properties": {
          "key_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          },
          "sig": {
            "type": "string",
            "pattern": "^[A-Za-z0-9_-]{86}$"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  },
  "record": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pubphys.com/protocol/schemas/record.json",
    "title": "record",
    "description": "pubphys.record/2 (SPEC section 4).",
    "type": "object",
    "required": [
      "author",
      "builds_on",
      "content_schema",
      "content_sha256",
      "created",
      "files",
      "origin",
      "parents",
      "salt",
      "schema",
      "site",
      "target",
      "type"
    ],
    "properties": {
      "schema": {
        "const": "pubphys.record/2"
      },
      "site": {
        "const": "pubphys.com"
      },
      "type": {
        "type": "string",
        "pattern": "^[a-z][a-z-]{0,39}$"
      },
      "content_schema": {
        "type": "string",
        "pattern": "^pubphys\\.content\\.[a-z][a-z-]{0,39}/[1-9][0-9]*$"
      },
      "content_sha256": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "files": {
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "id",
            "media_type",
            "name",
            "sha256",
            "size"
          ],
          "properties": {
            "id": {
              "type": "string",
              "pattern": "^[a-z0-9-]{1,40}$"
            },
            "name": {
              "type": "string"
            },
            "media_type": {
              "type": "string",
              "pattern": "^[a-z0-9][a-z0-9.+-]*/[a-z0-9][a-z0-9.+-]*$"
            },
            "size": {
              "type": "string",
              "pattern": "^(0|[1-9][0-9]*)$"
            },
            "sha256": {
              "type": "string",
              "pattern": "^[0-9a-f]{64}$"
            }
          },
          "additionalProperties": false
        }
      },
      "parents": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        }
      },
      "target": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{64}$"
      },
      "builds_on": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$"
        }
      },
      "author": {
        "type": "object",
        "required": [
          "account_ref",
          "orcid"
        ],
        "properties": {
          "orcid": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$"
          },
          "account_ref": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^[a-z0-9]{8,64}$"
          }
        },
        "additionalProperties": false
      },
      "origin": {
        "type": "object",
        "required": [
          "assisted_by",
          "kind"
        ],
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "human",
              "seed",
              "platform"
            ]
          },
          "assisted_by": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": false
      },
      "salt": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "created": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
      }
    },
    "additionalProperties": false
  }
};
